(function(){function r(e,n,t){function o(i,f){if(!n[i]){if(!e[i]){var c="function"==typeof require&&require;if(!f&&c)return c(i,!0);if(u)return u(i,!0);var a=new Error("Cannot find module '"+i+"'");throw a.code="MODULE_NOT_FOUND",a}var p=n[i]={exports:{}};e[i][0].call(p.exports,function(r){var n=e[i][1][r];return o(n||r)},p,p.exports,r,e,n,t)}return n[i].exports}for(var u="function"==typeof require&&require,i=0;i<t.length;i++)o(t[i]);return o}return r})()({1:[function(require,module,exports){
'use strict';

var _app = require('./config/app.constants');

var _app2 = _interopRequireDefault(_app);

var _app3 = require('./config/app.config');

var _app4 = _interopRequireDefault(_app3);

var _app5 = require('./config/app.run');

var _app6 = _interopRequireDefault(_app5);

require('./config/app.templates');

require('./components/about/aboutModule.js');

require('./components/core/coreModule.js');

require('./components/recent/recentModule.js');

require('./components/dashboard/dashboardModule.js');

require('./shared/article/articleModule.js');

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

// Add Stock view module

// Create and bootstrap application


// Import our templates file (generated by Gulp)
var requires = ['ui.router', 'templates', 'App.about', 'App.core', 'App.recent', 'App.article', 'App.dashboard'];

// Mount on window for testing


// Import our app functionaity
// Import our app config files
window.app = angular.module('App', requires);

angular.module('App').constant('AppConstants', _app2.default);

angular.module('App').config(['$stateProvider', '$urlRouterProvider', _app4.default]);

angular.module('App').filter('to_trusted', ['$sce', function ($sce) {
    return function (text) {
        return $sce.trustAsHtml(text);
    };
}]);

angular.module('App').run(_app6.default);

},{"./components/about/aboutModule.js":2,"./components/core/coreModule.js":3,"./components/dashboard/dashboardModule.js":6,"./components/recent/recentModule.js":7,"./config/app.config":8,"./config/app.constants":9,"./config/app.run":10,"./config/app.templates":11,"./shared/article/articleModule.js":12}],2:[function(require,module,exports){
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});
var aboutModule = angular.module('App.about', []);

exports.default = aboutModule;

},{}],3:[function(require,module,exports){
'use strict';

Object.defineProperty(exports, "__esModule", {
  value: true
});

var _headerController = require('./header/headerController');

var _headerController2 = _interopRequireDefault(_headerController);

var _footerController = require('./footer/footerController');

var _footerController2 = _interopRequireDefault(_footerController);

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

var coreModule = angular.module('App.core', []);

//coreModule.controller('headerController', HeaderCtrl);
coreModule.controller('footerController', _footerController2.default);

exports.default = coreModule;

},{"./footer/footerController":4,"./header/headerController":5}],4:[function(require,module,exports){
"use strict";

Object.defineProperty(exports, "__esModule", {
    value: true
});

var _createClass = function () { function defineProperties(target, props) { for (var i = 0; i < props.length; i++) { var descriptor = props[i]; descriptor.enumerable = descriptor.enumerable || false; descriptor.configurable = true; if ("value" in descriptor) descriptor.writable = true; Object.defineProperty(target, descriptor.key, descriptor); } } return function (Constructor, protoProps, staticProps) { if (protoProps) defineProperties(Constructor.prototype, protoProps); if (staticProps) defineProperties(Constructor, staticProps); return Constructor; }; }();

function _classCallCheck(instance, Constructor) { if (!(instance instanceof Constructor)) { throw new TypeError("Cannot call a class as a function"); } }

var FooterCtrl = function () {
    function FooterCtrl($scope) {
        _classCallCheck(this, FooterCtrl);

        $('#contact-us').hide();
    }

    // $("#sendFeedbackButton").click(function(){
    //     $("#sendFeedbackButton").hide();
    //     $("#contact-us").show();
    // });

    // $("#hideFeedbackButton").click(function(){
    //     $("#sendFeedbackButton").show();
    //     $("#contact-us").hide();
    // })

    // $("#contact-us").hide();

    _createClass(FooterCtrl, [{
        key: "toggleFeedback",
        value: function toggleFeedback() {
            $("#sendFeedbackButton").show();
            $("#contact-us").hide();
        }
    }]);

    return FooterCtrl;
}();

FooterCtrl.$inject = ['$scope'];

exports.default = FooterCtrl;

},{}],5:[function(require,module,exports){
// Work needed to make this work again
// class HeaderCtrl {
//     constructor($scope){
//         $scope.marketSegments = [];
//         initVariables();
//         initCanvas();
//         initListeners();

//         $scope.set = ($event) => {
//             $scope.sectorAnchor = $scope.sectorSet;
//             $scope.$apply();
//             $('#market-sector-header').css("color", $scope.textColor);
//             drawCircleMenu($scope.outerRadius, $scope.outerRadius, $scope.ctx, $scope.innerRadius, $scope.outerRadius, $scope.sectorAngle, $scope.angleWidth, $scope.marketSegments, $scope.sectorAngleAnchor);
//         }

//         $scope.update = ($event)=>{
//             if($event == false || typeof $event === 'undefined'){
//                 var mouse_x = 0;
//                 var mouse_y = 0;
//             }
//             else{
//                 var mouse_x = $event.clientX - $scope.circleMenuCanvas.left;
//                 var mouse_y = $event.clientY - $scope.circleMenuCanvas.top;
//             }

//             var angleOffset = $scope.sectorAngleAnchor;
//             var mangle = calcAngle($scope.outerRadius, mouse_x, mouse_y);
//             var mradius = calcRadius($scope.outerRadius, mouse_x, mouse_y);

//             drawCircleMenu(mangle, mradius, $scope.ctx, $scope.innerRadius, $scope.outerRadius, angleOffset, $scope.angleWidth, $scope.marketSegments);
//         }

//         function initVariables() {
//             $scope.marketSegments = ["Health Care", "Finance", "Consumables", "Real Estate", "Utilities", "Energy", "Materials", "Tech"];
//             //                    blue     green     grey    pink    yellow    red    brown     purple
//             //$scope.selectColor =["#c6dbe2", "#cbe2c6", "#e2c5c5", "pink", "#e2dfc6", "#e2c6c6", "#d3d2d5", "#cec6e2"];
//             $scope.selectColor = ["blue", "green", "salmon", 'pink', 'steelblue', 'cyan', 'seagreen', 'skyblue'];
//             $scope.outerRadius = 250;
//             $scope.innerRadius = $scope.outerRadius * 0.3;
//             $scope.angleWidth = 2*Math.PI/$scope.marketSegments.length;
//             $scope.sectorSet;
//             $scope.sectorAngle;
//             $scope.sectorAngleAnchor = $scope.angleWidth/2;
//             $scope.sectorAnchor = $scope.marketSegments[$scope.marketSegments.length - 1];
//             $scope.raf;
//             $scope.eventInProgress = false;
//             $scope.innerColor ="silver";
//             $scope.textColor;
//         }

//         function initCanvas(){
//             var myCanvas = document.getElementById('circle-menu');
//             $scope.circleMenuCanvas = myCanvas.getBoundingClientRect();
//             $scope.ctx = myCanvas.getContext('2d');
//             $scope.my_gradient=$scope.ctx.createRadialGradient($scope.outerRadius,$scope.outerRadius,0,$scope.outerRadius,$scope.outerRadius,$scope.outerRadius);
//             $scope.my_gradient.addColorStop(0,"gray");
//             $scope.my_gradient.addColorStop(1,"black");
//             window.onresize = function(){
//                 initCanvas();
//             }
//         }

//         function initListeners(){
//             $('#circle-menu').mousemove(function(event){
//                 event.stopPropagation();
//                 $scope.update(event);
//             });
//             $('#circle-menu').click(function(event){
//                 $scope.set(event);
//             })
//         }

//         function drawAnimatedArcs(canvasContext, canvas, circleRadius, drawRadius, angleWidth){
//             canvasContext.clearRect(0, 0, canvas.width, canvas.height);
//             canvasContext.beginPath(circleRadius, circleRadius);
//             canvasContext.translate();
//         }

//         function drawCircleMenu(mangle, mradius, canvasContext, innerRadius, outerRadius, angleOffset, angleWidth, marketSegments, startOffset = -1){
//             var angleOffsetStep;
//             var angleOffsetStepWidth;
//             if(startOffset == -1 || Math.abs(angleOffset - startOffset) < Math.PI/180){
//                 angleOffsetStep = angleOffset;
//             }
//             else if(angleOffset > startOffset){
//                 angleOffsetStep = startOffset;
//                 $scope.eventInProgress = true;
//             }
//             else{
//                 angleOffsetStep = startOffset - (Math.PI * 2);
//                 $scope.eventInProgress = true;
//             }
//             angleOffsetStepWidth = (angleOffset - angleOffsetStep)/5;
//             if(angleOffsetStepWidth < 0.001){
//                 angleOffsetStep = angleOffset;
//             }

//             if(!($scope.eventInProgress && startOffset == -1)){
//                 var persistentColor;
//                 for(var i = 0; i < marketSegments.length; i++)
//                 {
//                     var startAngle = (i* angleWidth + angleOffsetStep) %(Math.PI * 2);
//                     var thisAngle = Math.PI*2 - ((i*angleWidth + angleWidth/2) % (Math.PI*2));
//                     var selectColor = $scope.selectColor;
//                     var innerColor = $scope.innerColor;
//                     var color = $scope.my_gradient;
//                     var textColor = "white";
//                     if(startAngle >= Math.PI*2 - angleWidth){
//                         textColor = selectColor[i];
//                         persistentColor = textColor;
//                         color = "#555555";
//                     }
//                     if(startOffset == -1 && inAngle(mangle, startAngle, angleWidth) && inRadius(mradius, innerRadius, outerRadius)){
//                         $scope.sectorAngle = thisAngle;
//                         $scope.sectorSet = marketSegments[i];
//                         textColor = selectColor[i];
//                         $scope.textColor = textColor;
//                     }
//                     drawCircleMenuSegment(canvasContext, innerRadius, outerRadius, startAngle, angleWidth, color, marketSegments[i], textColor);
//                 }
//                 drawInnerCircle(canvasContext, innerRadius, outerRadius, innerColor);
//                 canvasContext.save();
//                 writeInnerLabel(canvasContext, outerRadius);
//                 canvasContext.restore();
//                 if((angleOffsetStep + angleOffsetStepWidth)%(Math.PI * 2) < angleOffset && $scope.sectorSet != 'Sector'){
//                     $scope.raf = window.requestAnimationFrame(function(){drawCircleMenu(mangle, mradius, canvasContext, innerRadius, outerRadius, angleOffset, angleWidth, marketSegments, startOffset + angleOffsetStepWidth)});
//                     $scope.sectorAngleAnchor = $scope.sectorAngle;
//                 }
//                 else{
//                     window.cancelAnimationFrame($scope.raf);
//                     $scope.eventInProgress = false;
//                 }
//             }
//         }

//         //    enlargeCircleMenu(canvasContext, innerRadius, outerRadius, angleWidth, innerColor, outerColor)
//         //    {
//         //        drawOuterSegment(canvasContext, outerRadius, -angleWidth/2, angleWidth, outerColor);
//         //        canvasContext.save();
//         //        drawInnerCircle(canvasContext, innerRadius, outerRadius, innerColor);
//         //        canvasContext.restore();
//         //    }

//         function drawCircleMenuSegment(canvasContext, innerRadius, outerRadius, startAngle, angleWidth, color, text, textColor){
//             drawOuterSegment(canvasContext, outerRadius, startAngle, angleWidth, color);
//             canvasContext.save();
//             writeOuterLabel(canvasContext, innerRadius, outerRadius, startAngle, angleWidth, text, textColor);
//             canvasContext.restore();
//         }

//         function drawOuterSegment(canvasContext, outerRadius, startAngle, angleWidth, color){
//             canvasContext.fillStyle = color;
//             canvasContext.beginPath();
//             canvasContext.moveTo($scope.outerRadius, $scope.outerRadius);
//             canvasContext.arc(outerRadius, outerRadius, outerRadius, startAngle, startAngle + angleWidth, false);
//             canvasContext.lineTo(outerRadius, outerRadius);
//             canvasContext.fill();
//         }

//         function writeOuterLabel(canvasContext, innerRadius, outerRadius, startAngle, angleWidth, text, textColor){
//             canvasContext.translate(outerRadius, outerRadius);
//             let centerAngle = startAngle + angleWidth/2;
//             let centerRadius = (innerRadius + outerRadius)/2;
//             canvasContext.beginPath();
//             canvasContext.font = "20pt Arial";
//             canvasContext.fillStyle = textColor;
//             canvasContext.textAlign = 'center';
//             canvasContext.textBaseline='middle';
//             canvasContext.fillText(text, Math.cos(centerAngle)*centerRadius, Math.sin(centerAngle)*centerRadius);
//         }

//         // Color in Hex
//         function drawInnerCircle(canvasContext, innerRadius, outerRadius, color="#f2f2f2"){
//             canvasContext.fillStyle = color;
//             canvasContext.beginPath();
//             canvasContext.arc(outerRadius, outerRadius, innerRadius, 0, 2*Math.PI, false);
//             canvasContext.fill();
//         }

//         function writeInnerLabel(canvasContext, outerRadius, text = 'Sector'){
//             canvasContext.translate(outerRadius, outerRadius);
//             canvasContext.beginPath();
//             canvasContext.font = "18pt Calibri";
//             canvasContext.fillStyle = 'black';
//             canvasContext.textAlign = 'center';
//             canvasContext.textBaseline='middle';
//             canvasContext.fillText(text, 0, 0);

//         }

//         function calcRadius(radius, x, y){
//             return Math.sqrt(Math.pow(x - radius, 2) + Math.pow(y - radius, 2));
//         }

//         function calcAngle(radius, x, y){
//             return (-Math.atan2(x-radius, y-radius)+Math.PI*2.5)%(Math.PI*2);
//         }

//         function inAngle(angle, startAngle, angleWidth){
//             return ((angle > startAngle  && angle < (startAngle + angleWidth)) ||
//                     ((angle > startAngle  || angle < (startAngle + angleWidth)%(Math.PI*2)) &&
//                     startAngle + angleWidth > Math.PI * 2));
//         }

//         function inRadius(radius, innerRadius, outerRadius){
//             return radius <= outerRadius && radius >= innerRadius;
//         }
//     }
// }

// HeaderCtrl.$inject = ['$scope'];

// export default HeaderCtrl;
"use strict";

},{}],6:[function(require,module,exports){
'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});
var dashboardModule = angular.module('App.dashboard', []);

dashboardModule.controller('dashboardController', ['$scope', function ($scope) {
    $.get('/stocklist').then(function (response) {
        $scope.$apply(function () {
            $scope.stock_list = response;
        });
    });

    $scope.addStock = function () {};
}]);

exports.default = dashboardModule;

},{}],7:[function(require,module,exports){
'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});
var recentModule = angular.module('App.recent', []);

recentModule.controller('recentController', ['$scope', '$state', function ($scope, $state) {
    $.get('/posts').then(function (posts) {
        $scope.$apply(function () {
            $scope.posts = posts;
        });
    });

    $scope.dateGeneration = function (ISOString) {
        return new Date(Date.parse(ISOString)).toDateString();
    };

    $scope.attachImage = function (odd_even) {
        var lastCard = $('card-row').last();
        var lastCardImage = $('.card-image').last();

        if (odd_even % 2) {
            lastCardImage.appendTo('card-row');
        } else {
            lastCardImage.prependTo('card-row');
        }
    };
}]);

exports.default = recentModule;

},{}],8:[function(require,module,exports){
'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});
function AppConfig($stateProvider, $urlRouterProvider) {

    var baseState = {
        name: 'base',
        url: '',
        views: {
            'header': {
                templateUrl: "components/core/header/header.html"
                // controller:"headerController"
            },
            'content': {
                template: '<div ui-view></div>'
            },
            'footer': {
                templateUrl: "components/core/footer/footer.html",
                controller: "footerController"
            }
        }
    };

    var blogState = {
        name: 'base.blog',
        url: '/blog',
        templateUrl: "components/recent/recentView.html",
        controller: 'recentController'
    };

    var learnState = {
        name: 'base.learn',
        url: '/learn',
        template: '<h1> Learn Sections Placeholder </h1>'
    };

    var resourcesState = {
        name: 'base.resources',
        url: '/resources',
        template: '<h1> Resources Section Placeholder </h1>'
    };

    var article = {
        name: 'base.article',
        url: '/article/:slug',
        templateUrl: "shared/article/articleView.html",
        controller: 'articleController'
    };

    var dashboardState = {
        name: 'base.dashboard',
        url: '/dashboard',
        templateUrl: 'components/dashboard/dashboardView.html',
        controller: 'dashboardController'
    };

    var aboutState = {
        name: 'base.about',
        url: '/about',
        template: '<h1> About Section Placeholder </h1>'
    };

    $stateProvider.state(baseState);
    $stateProvider.state(blogState);
    $stateProvider.state(learnState);
    $stateProvider.state(resourcesState);
    $stateProvider.state(article);
    $stateProvider.state(dashboardState);
    $stateProvider.state(aboutState);

    $urlRouterProvider.otherwise('');
};

AppConfig.$inject = ["$stateProvider", "$urlRouterProvide"];

exports.default = AppConfig;

},{}],9:[function(require,module,exports){
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
var AppConstants = {};

exports.default = AppConstants;

},{}],10:[function(require,module,exports){
'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});
function AppRun() {
    console.log('Finished loading dependencies and configuring modules');
};

exports.default = AppRun;

},{}],11:[function(require,module,exports){
'use strict';

angular.module('templates', []).run(['$templateCache', function ($templateCache) {
  $templateCache.put('components/dashboard/dashboardView.html', '<div class="dashboard">\r\n    <container ng-controller="dashboardController">\r\n        <table class="table">\r\n            <thead>\r\n                <tr>\r\n                    <th>Shares</th>\r\n                    <th>Ticker</th>\r\n                    <th>Name</th>\r\n                    <!-- # Shares, $ amount, or % of portfolio -->\r\n                    <th>Today\'s Return</th>\r\n                    <th>Total Return</th>\r\n                    <th>Action</th>\r\n                </tr>\r\n            </thead>\r\n            <tbody>\r\n                <tr>\r\n                    <td><input class="form-control" ng-model=\'stock.shares\'></td>\r\n                    <td><input class="form-control" ng-model=\'stock.ticker\'></td>\r\n                    <td></td>\r\n                    <td></td>\r\n                    <td></td>\r\n                    <td><button class="btn btn-primary" ng-click="addStock()">Add Stock</button></td>\r\n                </tr>\r\n                <tr ng-repeat="stock in stock_list">\r\n                    <td>{{stock.shares}}</td>\r\n                    <td>{{stock.ticker}}</td>\r\n                    <td>{{stock.name}}</td>\r\n                    <td>{{stock.today_return}}</td>\r\n                    <td>{{stock.total_return}}</td>\r\n                </tr>\r\n            </tbody>\r\n        </table>\r\n    </container>\r\n</div>');
  $templateCache.put('components/recent/recentView.html', '<div class="content" ng-controller=\'recentController\'>\r\n    <div class="container">\r\n        <div data-ng-repeat="post in posts">\r\n            <div class="card bg-dark text-white">\r\n                <div class="row no-gutters card-row">\r\n                    <div class="col">\r\n                        <div class="card-block px-2">\r\n                            <h2>\r\n                                <a data-ui-sref="base.article({slug:post.slug})" data-ui-sref-active="active">{{post.title}}</a>\r\n                            </h2>\r\n                            <div class="published_at">\r\n                                {{dateGeneration(post.created_at)}}\r\n                            </div>\r\n                            <p class="card-text"></p>\r\n                        </div>\r\n                    </div>\r\n                    <div class="col-auto">\r\n                        <a data-ui-sref="base.article({slug:post.slug})" data-ui-sref-active="active">\r\n                            <img class="recent-image" height="300"/>\r\n                        </a>\r\n                    </div>\r\n                </div>\r\n                <div class="card-footer w-100"></div>\r\n                <!--<img class="card-img-top recent-image" src="{{post.feature_image}}" alt="Card image cap"/>-->\r\n            </div>\r\n        </div>\r\n    </div>\r\n</div>\r\n');
  $templateCache.put('shared/article/articleView.html', '<div class="content" ng-controller="articleController">\r\n    <div class="container">\r\n        <h2> {{articleTitle}} </h2>\r\n        <div data-ng-bind-html="articleHtml | to_trusted"> </div>\r\n    </div>\r\n</div>\r\n');
  $templateCache.put('components/core/footer/footer.html', '<footer>\r\n    <button id="sendFeedbackButton" ng-click="toggleFeedback()" type="button" class="btn btn-default" aria-label="Send Feedback">\r\n        Feedback\r\n    </button>\r\n    <div id="contact-us">\r\n        <form>\r\n            <div class="form-group">\r\n                <label for="contactUsControlInput1">Email address</label>\r\n                <input type="email" class="form-control" id="contactUsControlInput1" placeholder="name@example.com">\r\n            </div>\r\n            <div class="form-group">\r\n                <label for="contactUsControlTextArea1">Feedback</label>\r\n                <textarea class="form-control" id="contactUsControlTextArea1" rows="3"></textarea>\r\n            </div>\r\n            <span>\r\n                <button class="btn btn-primary">Send</button>\r\n                <!-- <button id="hideFeedbackButton" type="button" class="btn btn-default" aria-hidden="true">Hide</button> -->\r\n            </span>\r\n        </form>\r\n    </div>\r\n</footer>\r\n');
  $templateCache.put('components/core/header/header.html', '<!--HEADER-->\r\n<nav class="navbar navbar-light">\r\n        <a data-ui-sref="base.dashboard" class="hide-desktop">\r\n            <img src="" alt="toggle menu" class="menu" id="menu">\r\n        </a>\r\n        <ul class="nav p show-desktop hide-desktop" id="nav">\r\n            <li class="nav-item">\r\n                <a class="nav-link" data-ui-sref = "base.dashboard" data-ui-sref-active="active"> Dashboard </a>\r\n            </li>\r\n            <li class="nav-item">\r\n                <a class="nav-link" data-ui-sref = "base.blog" data-ui-sref-active="active"> Blog </a>\r\n            </li>\r\n            <li class="nav-item">\r\n                <a class="nav-link" data-ui-sref = "base.learn" data-ui-sref-active="active"> Learn </a>\r\n            </li>\r\n            <li class="nav-item">\r\n                <a class="nav-link" data-ui-sref = "base.resources" data-ui-sref-active="active"> Resources </a>\r\n            </li>\r\n            <li class="nav-item">\r\n                <a class="nav-link" data-ui-sref = "base.about" data-ui-sref-active="active"> About </a>\r\n            </li>\r\n        </ul>\r\n</nav>\r\n<!-- <canvas id="circle-menu" width=500 height=500 data-ng-init="update(false)"></canvas> -->\r\n</div>');
}]);

},{}],12:[function(require,module,exports){
'use strict';

Object.defineProperty(exports, "__esModule", {
    value: true
});
var articleModule = angular.module('App.article', []);

articleModule.controller('articleController', ['$scope', '$stateParams', function ($scope, $stateParams) {
    var slug = $stateParams.slug;
    $.get('/article', { slug: slug }).then(function (post) {
        $scope.$apply(function () {
            $scope.articleTitle = post.title;
            $scope.articleHtml = post.html;
        });
    });
}]);

exports.default = articleModule;

},{}]},{},[1]);
