// Import our app config files
import constants  from './config/app.constants';
import appConfig  from './config/app.config';
import appRun     from './config/app.run';

// Import our templates file (generated by Gulp)
import './config/app.templates';

// Import our app functionaity
import './components/about/aboutModule.js';
import './components/core/coreModule.js';
import './components/recent/recentModule.js';

import './shared/article/articleModule.js';
// Add Stock view module

// Create and bootstrap application
const requires = [
  'ui.router',
  'templates',
  'App.about',
  'App.core',
  'App.recent',
  'App.article'
];

// Mount on window for testing
window.app = angular.module('App', requires);

angular.module('App').constant('AppConstants', constants);

angular.module('App').config(['$stateProvider', '$urlRouterProvider', appConfig]);

angular.module('App').filter('to_trusted', ['$sce', function($sce){
    return function(text){
        return $sce.trustAsHtml(text);
    };
}])

angular.module('App').run(appRun);